[package]
name = "dwim-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "dwim"
path = "main.rs"

[dependencies]
argh = "0.1.19"
crossterm = "0.29.0"
dirs = "7.0.0"
dwim-gpu.workspace = true
dwim-harness.workspace = true
dwim-models.workspace = true
unicode-width = "0.2.2"
ureq = "3.4.1"
