[package]
name = "dwim-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "dwim"
path = "main.rs"

[dependencies]
argh = "0.1.19"
crossterm = "0.29.0"
dirs = "7.0.0"
dwim-gpu = { version = "0.1.0", path = "../gpu" }
dwim-harness = { version = "0.1.0", path = "../harness" }
dwim-models = { version = "0.1.0", path = "../models" }
unicode-width = "0.2.2"
ureq = "3.4.1"
